name: Backend CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Product Service Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/product_service:latest ./backend/product_service/
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/product_service:latest

      - name: Build and Push Order Service Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/order_service:latest ./backend/order_service/
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/order_service:latest
